# Generated by Django 3.0.6 on 2020-07-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_reestractive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReestrActive',
        ),
    ]
