# Generated by Django 3.0.6 on 2020-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200723_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestractive',
            name='telNumber',
            field=models.CharField(max_length=50),
        ),
    ]
